#!/usr/bin/env bash

set -e
set -x

# FIXME: the check does not seem to work
# if ! brew_loc ="$(type -p "$brew")" || [[ -z $brew_loc ]]; then
#   echo Installing Homebrew
#   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#   echo >> /Users/alexey/.zprofile
#   echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/alexey/.zprofile
#   eval "$(/opt/homebrew/bin/brew shellenv)"
# fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_PLUGINS_DIR="dotbot-plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${DOTBOT_PLUGINS_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" \
--plugin-dir dotbot-plugins/dotbot-git \
--plugin-dir dotbot-plugins/dotbot-brew \
"${@}"
